version: 0.2

phases:
  install:
    commands:
      - echo Logging into Amazon ECR...
      - $(aws ecr get-login --region eu-west-2 --no-include-email)
  build:
    commands:
      - echo Building docker image
      - docker build -t $ECR_URI:latest .
  post_build:
    commands:
      - echo Pushing docker image
      - docker push $ECR_URI:latest