version: '3.8'
services:
  app:
    build: .
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=cockroachdb://root@crdb:26257/recipes
    ports:
      - '3000:3000'
  crdb:
    image: cockroachdb/cockroach:v22.2.6
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"