default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  adapter: cockroachdb
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  adapter: cockroachdb
  url: 'cockroachdb://root@127.0.0.1:26257/test?sslmode=disable'

production:
  <<: *default
  adapter: cockroachdb
  url: <%= ENV['DATABASE_URL'] %>
