apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipes-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - recipes.jamiebuckley.dev
      secretName:  recipes-app-certificate
  rules:
    - host: recipes.jamiebuckley.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipes-app
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recipes-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: recipes-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-app
  template:
    metadata:
      labels:
        app: recipes-app
    spec:
      containers:
        - name: recipes-app
          image: registry.jamiebuckley.dev/recipes-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
            - name: RAILS_LOG_TO_STDOUT
              value: "yes"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: recipes-secret-key
                  key: recipes-secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: recipes-database-url
                  key: recipes-database-url
            - name: ACCESS_KEY_ID
              valueFrom:
               secretKeyRef:
                 name: recipes-bucket-access
                 key: access-key
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: recipes-bucket-access
                  key: secret-key
            - name: GOOGLE_CLIENT_ID
              value: "788140346389-b73etchui30vrs9en35lnopuofm8vvjm.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: recipes-google-client-secret
                  key: secret
      imagePullSecrets:
        - name: regcred